### ISSUE TITLE
what about \OC ?

### ISSUE THREAD

**Issue by Rello** [ChristophWurst/nextcloud_composer#1]
Hello @ChristophWurst 
thank you for this package. I am using it in phpStorm and its perfect.

question: any suggestion on how to include also the OC stuff?
e.g.` \OC\Files\Filesystem::... `is getting complained several times

thank you

**Comment by ChristophWurst** [comment]
Hey :)

> thank you for this package. I am using it in phpStorm and its perfect.

Awesome :heart_eyes: 

> question: any suggestion on how to include also the OC stuff?

I've deliberately did not include the `OC` namespace because that's the private one of the Nextcloud server and you really shouldn't use it in any app because there is no deprecation policy or similar and the APIs can break/change/be removed at any time, even on minor releases.

So this is a wontfix for me. Having the `OC` stuff in apps like these would simply give wrong impressions of it being some kind of official API.

> question: any suggestion on how to include also the OC stuff?
> e.g.\OC\Files\Filesystem::...is getting complained several times

For those cases you should switch over to `OCP` interfaces/classes or if they are not available open a ticket in the server repo to discuss a public API.
