### ISSUE TITLE
Code contains references to OC namespace

### ISSUE THREAD

**Issue by hschletz** [ChristophWurst/nextcloud_composer#12]
I get errors like these:
> MissingDependency - [...] - OCP\Files\IRootFolder depends on class or interface oc\hooks\emitter that does not exist (see https://psalm.dev/157)

whenever my own code references an IRootFolder object.

This is different from #1: The OC namespace is referenced in the IRootFolder definition, not in my own code.

I can suppress these in the config:
```xml
<issueHandlers>
    <MissingDependency>
        <errorLevel type="suppress">
            <file name="[my own source file]" />
        </errorLevel>
    </MissingDependency>
</issueHandlers>
```
But that would suppress legitimate errors as well.

I don't want to inline the suppression every time I reference a NC class with possible OC references. The problem is not in my code and should not be handled there.

**Comment by ChristophWurst** [comment]
This is known, and not an issue of this package but the design of the Nextcloud public API. Psalm brought this to our attention a few months ago and we have since then applied a strict check on the OCP namespace in server: https://github.com/nextcloud/server/blob/7c3f8331ef560468fa4576cf19c7ceec94257389/.github/workflows/static-code-analysis.yml#L32-L56

These type leaks are also found for some of Nextcloud's dependencies. Like some of the APIs directly use Doctrone or Symfony. Then you get the same reports in an app.

This is not fixable here. We need to address these impurities in the server repo by restructuring some code.
